#!/usr/bin/env bash

export PATH=".:{PATH}"
export CVMFS_REPOSITORIES_EXCLUSIVE="alice.cern.ch,alice-ocdb.cern.ch"

ACTION="${1}"

if [[ "${ACTION}" == "enter" ]]; then
    shift
    ALI_MODULE="${2}"
    shift
    cvmfs2go /cvmfs/alice.cern.ch/bin/alienv enter VO_ALICE@${ALI_MODULE}
elif [[ "${ACTION}" == "load" ]]; then
    shift
    ALI_MODULE="${2}"
    shift
    /cvmfs/alice.cern.ch/bin/alienv printenv VO_ALICE@${ALI_MODULE} > sing_env
    cvmfs2go --env-file sing_env "${@}"
    rm -f sing_env
else
    cvmfs2go "${@}"
fi
