#!/usr/bin/env bash

CACHE="${HOME}/cvmfs-cache"
[[ -z "${SINGULARITY_CACHEDIR}" ]] && SINGULARITY_CACHEDIR="${HOME}/singularity-cache"
export SINGULARITY_CACHEDIR
mkdir -p ${CACHE} ${SINGULARITY_CACHEDIR}

help () {
echo "ALICE oriented script!! It will load and use alice.cern.ch,alice-ocdb.cern.ch
Singularity instance be be steered by env variable SINGULARITY_CVMFS2GO that should
contain the exact arguments string as would have been used in cli or by usage of any Singularity steering env variables
detailed at https://sylabs.io/guides/3.5/user-guide/appendix.html
The Singularity image path can be set arbitrary by the value of CVMFS2GO_IMGPATH
The container can be pre-setup by the usage of files prefixed with CVMFS2GO_EXEC_ or CVMFS2GO_LOAD_
in the current directory on home directory. (the ones from current directory take precedence)
If given as 1st argument a name that start with CVMFS2GO_LOAD_ it will be sourced before running a command or starting the shell
If given as 1st argument a name that start with CVMFS2GO_EXEC_ the first line of file will be executed
Command format: cvmfs2go command
If no command is used a bash shell will be started
N.B.!!! a $HOME/cvmfs-cache directory was created on host for keeping the cvmfs cache!
IT WILL _NOT_ BE CLEAN UP AUTOMATICALLY!!!
run : cvmfs2go cleanup
CVMFS_ALIEN_CACHE documentation specify that cache can be deleted even when in use
https://cvmfs.readthedocs.io/en/stable/cpt-configure.html#alien-cache"
}

[[ "${1}" == "help" ]] && { help; exit; }
[[ "${1}" == "cleanup" ]] && { rm -rf ${CACHE}/* ; exit; }

[[ -n "${SINGULARITY_BINDPATH}" ]] && export SINGULARITY_BINDPATH="${CACHE}:/var/lib/cvmfs,${SINGULARITY_BINDPATH}" || export SINGULARITY_BINDPATH="${CACHE}:/var/lib/cvmfs"
[[ -z "${SINGULARITY_SCRATCHDIR}" ]] && export SINGULARITY_SCRATCHDIR="/var/run/cvmfs"

CVMFS_REPOSITORIES="alice.cern.ch,alice-ocdb.cern.ch"
declare -a FUSEMOUNT_ARGS
IFS=',' read -ra repo_list <<< "${CVMFS_REPOSITORIES}"
for i in "${repo_list[@]}" ; do
    FUSEMOUNT_ARGS+=(--fusemount "\"container:cvmfs2 ${i} /cvmfs/${i}\"")
done

# Process additional singularity command line settings that can be setup by environment
declare -a SINGULARITY_CVMFS2GO_ARGS
[[ -n "${SINGULARITY_CVMFS2GO}" ]] && read -ra SINGULARITY_CVMFS2GO_ARGS <<< "${SINGULARITY_CVMFS2GO}"

# Specify the location of Singularity image
if [[ -z "${CVMFS2GO_IMGPATH}" ]]; then
    NAME="el7cvmfs.sif"
    singularity pull --name ${NAME} shub://adriansev/cvmfs2go:latest &> /dev/null
    export CVMFS2GO_IMGPATH="${NAME}"
fi

exec singularity -s run "${FUSEMOUNT_ARGS[@]}" "${SINGULARITY_CVMFS2GO_ARGS[@]}" ${CVMFS2GO_IMGPATH} "${@}"

